name: Trdl publisher
on:
  push:
    branches:
    - trdl

jobs:
  release:
    name: Publish release channels using trdl server
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      uses: werf/trdl-vault-actions/publish@main
      with:
        vault-addr: ${{ secrets.TRDL_VAULT_ADDR }}
        project-name: kubedog
        vault-auth-method: approle
        vault-role-id: ${{ secrets.TRDL_VAULT_ROLE_ID }}
        vault-secret-id: ${{ secrets.TRDL_VAULT_SECRET_ID }}

